// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClsUGHSmROdJCjHZxBSig-9E02HFRl69s',
    appId: '1:409687699195:web:c7d3cb64a675c41b500a5e',
    messagingSenderId: '409687699195',
    projectId: 'final-year-project-48d4e',
    authDomain: 'final-year-project-48d4e.firebaseapp.com',
    storageBucket: 'final-year-project-48d4e.appspot.com',
    measurementId: 'G-9Y2XN08HDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL4Nml_6SZf2U2udZCawC62tjxHylXOsk',
    appId: '1:409687699195:android:b5473e8664efb406500a5e',
    messagingSenderId: '409687699195',
    projectId: 'final-year-project-48d4e',
    storageBucket: 'final-year-project-48d4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAS-Q0CgyndK-BntTknUqqLJSvrXl3z5k',
    appId: '1:409687699195:ios:176765b9359d6d79500a5e',
    messagingSenderId: '409687699195',
    projectId: 'final-year-project-48d4e',
    storageBucket: 'final-year-project-48d4e.appspot.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAS-Q0CgyndK-BntTknUqqLJSvrXl3z5k',
    appId: '1:409687699195:ios:cc2821cde989fc74500a5e',
    messagingSenderId: '409687699195',
    projectId: 'final-year-project-48d4e',
    storageBucket: 'final-year-project-48d4e.appspot.com',
    iosBundleId: 'com.example.fyp.RunnerTests',
  );
}
